irphilli/tracker_api

- lib/tracker_api/resources/base.rb
Hi, there. I found deprecation warning. 
please, fix it.
> DEPRECATION WARNING: `#reset_changes` is deprecated and will be removed on
Rails 5. Please use `#clear_changes_information` instead.
> Fix DEPRECATION WARNING for Rails5

- lib/tracker_api.rb
- require active_support/core_ext for blank? method
- https://github.com/dashofcode/tracker_api/blob/v0.2.8/lib/tracker_api/client.rb#L189
Other fix method.
```diff
- if (method == :post || method == :put) && options[:body].blank?
+ if (method == :post || method == :put) && (options[:body].nil? || options[:body].empty?)
```
> Fix `undefined method blank?'

- tracker_api.gemspec
This is needed because older versions of activemodel cause an exception to occur.
> Issue #43 fix: Updated gemspec with minimum version of activemodel

- lib/tracker_api.rb
This eliminates a warning when running in Rails.
```bash
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/tracker_api-0.2.10/lib/core_ext/object/blank.rb:103:warning: already initialized constant String::BLANK_RE
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/blank.rb:102:warning: previous definition of BLANK_RE was here
```
> Conditionally load core_ext/blank depending on AS

- lib/tracker_api/client.rb
This is helpful to add instrumentation or other middleware to the Faraday connection.
> Support passing in a block to initialize

- lib/tracker_api.rb
- lib/tracker_api/client.rb
- tracker_api.gemspec
Change to depend on the multi_json gem instead of Oj so that the tracker_api can
be used as part of jruby as well. The multi_json gem will default to using Oj if
it is available anyway.
> Remove direct dependency on Oj for use with jruby

- lib/tracker_api/resources/epic.rb
For my project I need to know, if epic is closed. 
So I want add "completed_at" field to epic resource.
> Add completed_at field to epics resource

- lib/tracker_api/resources/story.rb
> Added after_id & before_id support for Story

- lib/tracker_api/client.rb
- lib/tracker_api/endpoints/workspace.rb
Hey guys,
We needed a `#create_workspace` method, so here it is.
> Initial implementation of #create_workspace

- README.md
I made the mistake of assuming the README was updated and tried working with the really old version of the gem mentioned. I think to be safe, the version should just be removed from the readme, and let the user decide how to setup their gemspec file.
> updating readme to remove old version of gem

- lib/tracker_api/resources/story.rb
- test/story_test.rb
This might be an acceptable compromise to not supporting `<<` for `owner_ids`. Also consistent with the `add_label` interface which exists for the same reasons.
> Added story#add_owner

- README.md
Doesn't seem to be supported anymore.
```ruby
:body=>{
"code"=>"invalid_parameter",
"kind"=>"error",
"error"=>"One or more request parameters was missing or invalid.",
"general_problem"=>"Specifying sub-tree for 'comments' is not supported"
}
```
> "Specifying sub-tree for 'comments' is not supported"

- tracker_api.gemspec
'faraday_middleware' has already set a dependency of faraday.
So, I think able to delete faraday's dependency.
> relax dependency of faraday.

- .travis.yml
- lib/tracker_api/client.rb
- test/minitest_helper.rb
Fixes #123 
Currently `excon` does not work out of the box with Jruby due to a more restrictive cipher set.  In order to prevent usability issues this sets the default adapter to `net_http` for Jruby
> Use net_http as default HTTP adapter for Jruby

- lib/tracker_api/resources/story.rb
This was referenced in [issue 68](https://github.com/dashofcode/tracker_api/issues/68), but never resolved. 
Previously, you could not update a `story`'s `project_id` like you could for other `attributes` of a `story`. In TrackerAPI::Endpoints::Story, a `PUT` request was made to a URL formed with the `story`'s dirty `project_id`, which would return a 404. Instead, we need to form this URL with the story's original `project_id`.
> Add support for moving stories between projects

- lib/tracker_api/client.rb
- lib/tracker_api/error.rb
- test/error_test.rb
A [recent Faraday update](https://github.com/lostisland/faraday/tree/v0.16.1) re-organized their error classes and added a new one. This PR updates references to deprecated classes and includes the new one.
> Update Faraday error handling

- test/client_test.rb
- test/comment_test.rb
- test/file_attachment_test.rb
- test/minitest_helper.rb
- test/project_test.rb
- test/release_test.rb
- test/story_test.rb
- test/task_test.rb
- test/workspace_test.rb
- Avoids deprecation warning when requiring mocha/minitest for certain versions of mocha
- Replaces deprecated global usage of minitest assertions
> Fix minitest deprecations

- lib/tracker_api.rb
- lib/tracker_api/file_utility.rb
- tracker_api.gemspec
To address: https://github.com/ProductPlan/tracker_api/issues/144 and https://github.com/ProductPlan/tracker_api/issues/143
Switch to `mini_mime` similar to what Rails did: https://github.com/rails/rails/commit/7c55e373be1d40a72581cb6d4131eb2d9e0c2fcb
Not really a necessary change now that `mimemagic` has released new versions with MIT licenses 🤷 .
> Replace mimemagic with mini_mime

- .github/workflows/ruby-tests.yml
- Gemfile
- README.md
- test/minitest_helper.rb
We're already using CodeClimate for maintainability. Might as well bring in coverage as well!
> build: use codeclimate for coverage

- README.md
Using an SVG instead of a png for the gem version in the README.  Also, just opening this up so that we can create a pull request reference in tracker to create tests around pull requests!
> docs: use svg instead of png for gem version image (svg is sharper!)

- .github/workflows/ruby-tests.yml
- README.md
- Ruby 2.5 was EOL several months ago, so will remove official support for it
- Officially support Ruby 3.0 and 3.1
> build: drop ruby 2.5 from CI and add 3.0 and 3.1

- .github/workflows/ruby-tests.yml
- gemfiles/faraday-1.gemfile
- gemfiles/faraday-2.gemfile
- lib/tracker_api.rb
- lib/tracker_api/client.rb
- lib/tracker_api/logger.rb
- tracker_api.gemspec
This brings in faraday 2.0 support by:
- Dropping `faraday_middleware`. Common middleware now bundled with newer versions of Faraday.
- Simplifying our dependencies by dropping `excon`. Users can still choose to use that adapter with options, but we will default to `net_http`.
- Requiring Faraday >= 1.10. Faraday 1.10 is the lowest version on the 1.x branch that has most of the middleware we need bundled in.
- Updating our build matrix to test against multiple versions of Faraday.
> faraday 2 support

- lib/tracker_api/resources/epic.rb
Exposes the `projected_completion` attribute from the Pivotal API on the epic resource
```ruby
client = TrackerApi::Client.new(token: token)
project = client.project(project_id)
epics = project.epics(fields: ":default,followers,projected_completion")
projected_completion = epics.first.projected_completion
```
https://www.pivotaltracker.com/help/api/rest/v5#epic_resource
> Add projected completion date for epics

- .github/workflows/ruby-tests.yml
- test/minitest_helper.rb
Truffleruby tests seem to have an issue with calculating coverage. Only run coverage when we need it.
> ci: conditionally run coverage

- lib/tracker_api/resources/project.rb
Exposes the `status` attribute from the Pivotal API on the project resource.
```ruby
client = TrackerApi::Client.new(token: token)
project = client.project(project_id, fields: ':default,status')
puts(project.status)
```
https://www.pivotaltracker.com/help/api/rest/v5#project_resource
> Add status attribute for project

- .github/workflows/ruby-tests.yml
2.7 and 3.0 are EOL, so no longer officially supported.
> ci: add ruby 3.3 to test matrix and remove 2.7, 3.0
